# version: '3.9'

services:
  app:
    build: .
    container_name: app_service
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "8000:8000"
    restart: unless-stopped

# We have also removed the top-level 'volumes: ollama_data'